### ISSUE TITLE
Charts scaling

### ISSUE THREAD

**Issue by siulynot** [KomodoPlatform/BarterDEX#10]
Chart scaling is not as it should be. It seems the scaling makes the candles flat. Maybe it is because logarithmic scaling is set by default and since the price movements are not significant enough... the log scale makes the chart look awful. 

Maybe removing log scale by default can help. Also, defaul should be something more like 15min timescale or even maybe a 1h scale.

**Comment by petitPapillon** [comment]
@siulynot 
The chart values are not actually scaled in any way. The original values that are received through the API are displayed on the chart.
https://imgur.com/a/kWMoo
In the image above you can see some of the values. The row is consisted of: timestamp, open, high, low, close, volume.
As it can be seen in the image, the values for open, high, low and close are the same, that's why the candles are flat.
I guess 1 minute (the current default time frame) is not enough time for the price to change in any meaningful way.

https://imgur.com/a/L4Xte - here's how the chart looks like with a 1h time frame.

Maybe we should go with 1h as the default time frame.

**Comment by siulynot** [comment]
@petitPapillon 
In that case we can try to set default timescale to 1hr... that way there is a better view of the charts once they start collecting data.
