### ISSUE TITLE
When trying to switch trade coin to another one, and pushing [enable electrum] nothing happens

### ISSUE THREAD

**Issue by kjpeee** [KomodoPlatform/BarterDEX#39]
By default when choosing another coin it's disabled by default (always have to choose electrum/native before trades). Ideally in preferences there hsould be an option to choose one of this parameter by default and always use it.

Anyway, actual problem is that when you changing to the other currencyand pushing "enable electrum" nothing happens. For some coins if I press refresh sveral times in various places eventually trading window appears (which is wrong as well, system should respond/refresh automatically) -  but for example below manual refersh didn't helped.
![image](https://user-images.githubusercontent.com/26009915/34618350-8985098a-f24f-11e7-8a34-20337fce44d4.png)

**Comment by satindergrewal** [comment]
>pushing "enable electrum" nothing happens. 

If nothing happens, then that coin doesn't have Electrum Server. Install its Native coin and setup it's RPC settings and then use `Native Mode` to activate/enable it.

>For some coins if I press refresh sveral times in various places eventually trading window appears (which is wrong as well, system should respond/refresh automatically) - but for example below manual refresh didn't helped.

Not clear what you are saying. Which refresh button? There are many refresh buttons at many places in Exchange screen.

It is possible that refresh may take a tiny bit of time providing output, especially in case of coins activated in Electrum Mode. Electrum Mode is slower than `Native Mode`, and based on internet connection speed it may act slower/faster on end user's computer. If you really are after the speedy response, I suggest you try Native Mode.

Not sure if you are complaining about switch coin button. But in case you are, you should try Github repo ReadMe instructions to try the Github repo installation. There's one issue with Switch Pairs button which is fixed in repo, and will be released on next release whenever it will happen.
