### ISSUE TITLE
Coin request: Decred

### ISSUE THREAD

**Issue by sneurlax** [KomodoPlatform/BarterDEX#59]
Hi.  Title says it all!

If I were to contribute this, a quick tip on where to start would be appreciated :)

**Comment by cipig** [comment]
Hi. I tried to integrate DCR and failed. After start BarterDEX imports the smartaddress into the respective wallet, but fails to do this with DCR. The error message from the wallet is "imported addresses must belong to the imported account". When you try it on commandline, same result. Something like `importaddress <dcraddress> "mysuperbarterdexaccount"` simply fails with the above error message. For some unknown reason the DCR wallet insists in importing new addresses only into the account called "imported" or something like that. If you can change this behaviour, so that the wallet lets me import new addresses and name the account as i like, then we would be one step further.
