### ISSUE TITLE
UX comments

### ISSUE THREAD

**Issue by psimondo** [KomodoPlatform/BarterDEX#71]
Given how BarterDex works and how different it is to a regular centralised exchange, some things need to be made a lot more explicit in the UI to avoid user confusion.

For example, on a centralised exchange, when an order is placed, it immediately shows up in the order book or under 'open orders'. It's instant, even if the trade itself is not. In BarterDex, when placing an order, there is a lack of UI feedback telling the user that something is actually going on.

1. When an order is placed, it should appear immediately in trade history, trade status, my offers. Even if it is clearly marked as 'unconfirmed' to start, then the UI should make explicit what is actually going on:
- order submitted to DEX
- counterparty found
- counterparty deposit paid
- atomic swap proceeding
- etc
In short, there needs to be some indication that something is going on or it looks broken, especially if you are used to a regular exchange. It also helps educate people about how Atomic Swap magic happens.

2. In the Dashboard, it would be useful to be able to inspect your UTXO's for each coin and break up your own wallet (for a fee) into more UTXO's to maximise your chances of a particular trade. This would educate people about how matching with UTXO's work. 

3. If a trade fails to match because of incompatible UTXO's with offering parties, it's confusing. The UI should offer some feedback about what's happening or when it fails completely and what the user can do to improve it (perhaps offering to create additional UTXO's for a fee). Right now, they'd have to read the whitepaper to find out.

4. Tooltips over some interface elements would be really helpful. especially on the exchange screens. Specifically.
- UTXO's
- Credits
- Ave volume
- Age
- Depth
- Options for repeating orders. (Users of regular exchanges would have no idea why they would ever need such a thing).

Thanks. It's amazing tech and it works. I hope this is helpful and not irritating!

**Comment by satindergrewal** [comment]
Thanks for taking some time to write it and your feedback.

1. if It was a GUI level issue to display things immediately, trust me, I would have done that from the beginning. I can not falsely display the status in case the atomic swap hasn't even started, or even in case the trade order isn't triggered by the API but I instead display it in the My Offers/Orders tab. I have no control over making the API, and it's speed of giving outputs. Any data which is provided by API is displayed in a matter of seconds in the GUI. So, any request on displaying the data as quick as possible, I guess you have to ask @jl777. He can help better in that part I think.

2. We tried the UTXO auto-splitter GUI earlier. I provided nice sliders and set of utxo values a user could split the total balance into multiple UTXOs, and that only for a single transaction fee, the cheapest way to split the balance to multiple UTXOs. But that didn't work out much well, from the network's load point of view and also from the required UTXO needed to make a trade for a different set of pairs. So, the UTXO auto-splitter GUI discontinued in later versions.
But this UTXO splitting option is still available alternatively in the GUI. If you need a specific UTXO to make a trade, just select the receiving address of your BarterDEX smart address and send the amount to your own smart address by going to send coins dialog box. When sending a transaction to make a UTXO to your own address, there are conditions added in the GUI code which adds extra set of UTXOs, which makes sure it gives you the UTXO that you need, and also has the change balance created for further auto split UTXO which are done automatically as you keep trading.

3. If the trade fails to match, the GUI shows the two different versions of a dialog box with quick help on what amount of UTXO they need to make that same trade happen. In case the UTXO required is bigger than the total balance of the coins' address, then it asks to send that amount to BarterDEX coin's smartaddress, else, it shows the amount, and fee it will require to create the desired UTXO, and shows send button. After user sends that transaction to the wallet, wait for a minute or so so that the transaction is confirmed on the blockchain, and then try the same trade.

The only thing which is tricky here is that it is very much blockchain based stuff. The regular user most probably will get confused with the heavy technical terms like UTXOs, smart address, confirmations, explorer and so on etc. That is the biggest reason I don't refer this BarterDEX to any new users. It is only for the users who are Blockchain educated. The first movers. The first explorers. The Power users.

In case you find the wording need change to these two different versions of the dialog boxes, please let me know. or you can find the wording in language file and can possibly make changes and make a Github PR request with your changes.
https://github.com/KomodoPlatform/BarterDEX/tree/v0.8/assets/languages

4. Yes, I should take some time to add the tooltip to all places where applicable in the GUI.

**Comment by psimondo** [comment]
1. I guessed it was something along these lines. I'll send my specific comments to @jl777. Basically anything that can be done to keep the user informed a bit better would improve the experience dramatically.

2. Interesting. How to best shield the user from UTXO complexity is truly complicated. Optimally they wouldn't see it or have to think about it. Next best, when loading a new coin to work with, the UI could suggest that users immediately "organise their wallets to improve the odds of trade success" by creating a whole bunch of different UTXO's immediately - BUT I assume this approach has the load issues you mention. I guess another option is to automate the more limited example you mention - creating the specific UTXO you need for a specific transaction when needed? It's really tough!

3. I must have been presented with one of these options. I don't recall exactly. I do recall being confused. I'll look at the wording.

Thanks for replying. It's really great work. Any comments I intend to be helpful and if there is anything you'd like me to look at, I'm happy to do so.
